# Makefile.test - The Garnata Retrieval System
# Copyright (C) 2005, 2026 Alfonso E. Romero
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Makefile for the test programs


SRC=src
SRCTEST=test
OBJ=obj
OBJTEST=objtest
BIN=bintest
LIB=lib
INC=include
COMP=compression
CXX=g++
CXXFLAGS=-g -O3 -pipe -W -Wall


all : testCompression testOccurrence testUnit

#########################################################

testOccurrence : $(OBJTEST)/testOccurrence.o $(OBJ)/Occurrence.o $(OBJ)/Lexicon.o $(OBJ)/Term.o $(OBJ)/Globals.o $(LIB)/libcompress.a
	$(CXX) -o $(BIN)/testOccurrence $^

testCompression : $(OBJTEST)/testCompression.o $(LIB)/libcompress.a
	$(CXX) -o $(BIN)/testCompression $^

testUnit : $(OBJTEST)/testUnit.o $(OBJ)/Unit.o $(OBJ)/UnitReader.o $(LIB)/libcompress.a
	$(CXX) -o $(BIN)/testUnit $^

$(LIB)/libcompress.a : 
	make -f Makefile.compression

$(OBJTEST)/testCompression.o : $(COMP)/testCompression.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJTEST)/testUnit.o : $(SRCTEST)/testUnit.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJTEST)/testOccurrence.o : $(SRCTEST)/testOccurrence.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJ)/Occurrence.o : $(SRC)/Occurrence.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJ)/Lexicon.o : $(SRC)/Lexicon.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJ)/Term.o : $(SRC)/Term.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJ)/Unit.o : $(SRC)/Unit.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

$(OBJ)/UnitReader.o : $(SRC)/UnitReader.cpp
	$(CXX) -c $(CXXFLAGS) $< -I $(INC) -o $@

 