# Makefile.compression - The Garnata Retrieval System
# Copyright (C) 2005, 2026 Alfonso E. Romero
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

#####################################################
# Makefile for the Garnata Retrieval System: compression library
# Alfonso E. Romero 
# <aromero@correo.ugr.es>
# April, 2006
#####################################################


#####################################################################
# Predefined vars
#####################################################################

CXX=g++
CFLAGS=-c -g -O3 -pipe -W -Wall -std=c++11 -pedantic
OBJ=./obj
SRC=./compression
LIB=./lib
	
#####################################################################
# Library 
#####################################################################

all: libcompress

libcompress : $(OBJ)/BasicInputBinaryBuffer.o $(OBJ)/BasicOutputBinaryBuffer.o \
	$(OBJ)/InputCompressedBinaryFile.o $(OBJ)/OutputCompressedBinaryFile.o $(OBJ)/VariableByteCoder.o \
	$(OBJ)/InputIndexFile.o $(OBJ)/OutputIndexFile.o
	ar r $(LIB)/libcompress.a $(OBJ)/BasicInputBinaryBuffer.o $(OBJ)/BasicOutputBinaryBuffer.o \
		$(OBJ)/InputCompressedBinaryFile.o $(OBJ)/OutputCompressedBinaryFile.o $(OBJ)/OutputIndexFile.o \
		$(OBJ)/InputIndexFile.o $(OBJ)/VariableByteCoder.o

#####################################################################
# library object files
#####################################################################
		
$(OBJ)/BasicInputBinaryBuffer.o : $(SRC)/BasicInputBinaryBuffer.cpp
	$(CXX) $(CFLAGS) $(SRC)/BasicInputBinaryBuffer.cpp -o $(OBJ)/BasicInputBinaryBuffer.o 
	
$(OBJ)/BasicOutputBinaryBuffer.o : $(SRC)/BasicOutputBinaryBuffer.cpp
	$(CXX) $(CFLAGS) $(SRC)/BasicOutputBinaryBuffer.cpp -o $(OBJ)/BasicOutputBinaryBuffer.o
	
$(OBJ)/InputCompressedBinaryFile.o : $(SRC)/InputCompressedBinaryFile.cpp 
	$(CXX) $(CFLAGS) $(SRC)/InputCompressedBinaryFile.cpp -o $(OBJ)/InputCompressedBinaryFile.o
	
$(OBJ)/OutputCompressedBinaryFile.o : $(SRC)/OutputCompressedBinaryFile.cpp 
	$(CXX) $(CFLAGS) $(SRC)/OutputCompressedBinaryFile.cpp -o $(OBJ)/OutputCompressedBinaryFile.o

$(OBJ)/OutputIndexFile.o : $(SRC)/OutputIndexFile.cpp 
	$(CXX) $(CFLAGS) $(SRC)/OutputIndexFile.cpp -o $(OBJ)/OutputIndexFile.o

$(OBJ)/InputIndexFile.o : $(SRC)/InputIndexFile.cpp 
	$(CXX) $(CFLAGS) $(SRC)/InputIndexFile.cpp -o $(OBJ)/InputIndexFile.o

$(OBJ)/VariableByteCoder.o : $(SRC)/VariableByteCoder.cpp
	$(CXX) $(CFLAGS) $(SRC)/VariableByteCoder.cpp -o $(OBJ)/VariableByteCoder.o

#####################################################################
	
clean : 
	\rm $(OBJ)/*
	
#####################################################################

