#!/bin/bash
# postInstall - The Garnata Retrieval System
# Copyright (C) 2005, 2026 Alfonso E. Romero
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Post-install script - The Garnata Retrieval System
# (c) Alfonso E. Romero, 2005
# 

####################################################


echo "Would you like to:"
echo "1.- store indexes on your home space (in ~/.garnata)? or"
echo "2.- store them in other place?"
echo -n "enter the number of the desired option: "

read var

case "$var" in
	[1] ) mkdir ~/.garnata ;;
  [2] ) echo -n "Enter the absolute path of the directory to store indexes: "
        read direct
        echo "Creating symbolic link..."
        ln -s direct ~/.garnata
        ;;
  *   ) echo "Bad option. Exiting"
      exit -1;;
esac

####################################################

echo "Creating auxiliary directories..."

mkdir ~/.garnata/collections
mkdir ~/.garnata/indexes
mkdir ~/.garnata/weight
mkdir ~/.garnata/stopwords

####################################################

echo "Creating configuration file..."

cat > ~/.garnata/conf_file <<EOD
0
1
EOD

####################################################

